-- Migración simple para Health Auto Export
-- Ejecutar en PostgreSQL

-- 1. Agregar campos a DATOS_VITALES
ALTER TABLE DATOS_VITALES ADD COLUMN IF NOT EXISTS FECHA_MEDICION TIMESTAMP;
ALTER TABLE DATOS_VITALES ADD COLUMN IF NOT EXISTS DISPOSITIVO VARCHAR(100);
ALTER TABLE DATOS_VITALES ADD COLUMN IF NOT EXISTS FUENTE VARCHAR(100);

-- 2. Actualizar registros existentes
UPDATE DATOS_VITALES SET FECHA_MEDICION = FECHA_REGISTRO WHERE FECHA_MEDICION IS NULL;

-- 3. Crear tabla de configuración
CREATE TABLE IF NOT EXISTS HEALTH_AUTO_EXPORT_CONFIGS (
    ID SERIAL PRIMARY KEY,
    USUARIO_ID INTEGER NOT NULL,
    API_KEY VARCHAR(100) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_SYNC_AT TIMESTAMP NULL,
    ALLOWED_DATA_TYPES VARCHAR(1000) NULL,
    DEVICE_INFO VARCHAR(500) NULL,
    SYNC_INTERVAL_MINUTES INTEGER NOT NULL DEFAULT 60,
    CONSTRAINT FK_HEALTH_AUTO_EXPORT_CONFIGS_USUARIOS 
        FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID) ON DELETE CASCADE
);

-- 4. Crear índices
CREATE UNIQUE INDEX IF NOT EXISTS IX_HEALTH_AUTO_EXPORT_CONFIGS_API_KEY 
ON HEALTH_AUTO_EXPORT_CONFIGS (API_KEY);

CREATE INDEX IF NOT EXISTS IX_HEALTH_AUTO_EXPORT_CONFIGS_USUARIO 
ON HEALTH_AUTO_EXPORT_CONFIGS (USUARIO_ID);

-- 5. Crear usuario 7 si no existe
INSERT INTO USUARIOS (
    ID, NOMBRE, APELLIDO, EMAIL, PASSWORD, 
    FECHA_NACIMIENTO, GENERO, ALTURA, PESO, 
    FECHA_REGISTRO, ULTIMO_ACCESO, ES_PROFESIONAL_MEDICO,
    ROL, ES_ACTIVO
) 
SELECT 
    7, 'Usuario', 'Health Auto Export', 'healthautoexport@healthpredict.com', 
    'password123', '1990-01-01', 'Otro', 170, 70, 
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE,
    'Trabajador', TRUE
WHERE NOT EXISTS (SELECT 1 FROM USUARIOS WHERE ID = 7);

-- 6. Crear configuración inicial
INSERT INTO HEALTH_AUTO_EXPORT_CONFIGS (
    USUARIO_ID, API_KEY, IS_ACTIVE, ALLOWED_DATA_TYPES
)
SELECT 
    7, 'HAE' || EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::TEXT || 'USER7', TRUE,
    '["stepcount","heartrate","bloodpressuresystolic","bloodpressurediastolic","bloodglucose","bodyweight","bodytemperature","oxygensaturation","sleepanalysis","activeenergyburned","distancewalking","vo2max","restingheartrate","walkingheartrateaverage","respiratoryrate"]'
WHERE NOT EXISTS (SELECT 1 FROM HEALTH_AUTO_EXPORT_CONFIGS WHERE USUARIO_ID = 7);

-- 7. Mostrar configuración
SELECT 
    'Health Auto Export configurado' as MENSAJE,
    API_KEY,
    CREATED_AT
FROM HEALTH_AUTO_EXPORT_CONFIGS 
WHERE USUARIO_ID = 7; 