-- Script para crear las tablas base de HealthPredict
-- Ejecutar en PostgreSQL

-- Crear tabla USUARIOS
CREATE TABLE IF NOT EXISTS USUARIOS (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVO BOOLEAN DEFAULT TRUE,
    ROL VARCHAR(50) DEFAULT 'Usuario',
    DEPARTAMENTO VARCHAR(100),
    CARGO VARCHAR(100),
    TELEFONO VARCHAR(20),
    FECHA_NACIMIENTO DATE,
    GENERO VARCHAR(10),
    ALTURA DECIMAL(5,2),
    PESO_INICIAL DECIMAL(5,2),
    CONDICIONES_MEDICAS TEXT,
    MEDICAMENTOS TEXT,
    CONTACTO_EMERGENCIA_NOMBRE VARCHAR(100),
    CONTACTO_EMERGENCIA_TELEFONO VARCHAR(20),
    PREFERENCIAS_NOTIFICACION TEXT,
    ZONA_HORARIA VARCHAR(50) DEFAULT 'UTC',
    IDIOMA VARCHAR(10) DEFAULT 'es',
    FECHA_ULTIMA_ACTIVIDAD TIMESTAMP,
    INTENTOS_LOGIN_FALLIDOS INTEGER DEFAULT 0,
    CUENTA_BLOQUEADA BOOLEAN DEFAULT FALSE,
    FECHA_ULTIMO_CAMBIO_PASSWORD TIMESTAMP,
    TOKEN_RECUPERACION VARCHAR(255),
    FECHA_EXPIRACION_TOKEN TIMESTAMP,
    AVATAR_URL VARCHAR(500),
    CONFIGURACION_PRIVACIDAD TEXT,
    ACEPTA_TERMINOS BOOLEAN DEFAULT FALSE,
    FECHA_ACEPTACION_TERMINOS TIMESTAMP
);

-- Crear tabla DATOS_VITALES
CREATE TABLE IF NOT EXISTS DATOS_VITALES (
    ID SERIAL PRIMARY KEY,
    USUARIO_ID INTEGER NOT NULL REFERENCES USUARIOS(ID) ON DELETE CASCADE,
    TIPO_DATO VARCHAR(50) NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    UNIDAD VARCHAR(20),
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MEDICION TIMESTAMP,
    DISPOSITIVO VARCHAR(100),
    FUENTE VARCHAR(100),
    NOTAS TEXT,
    VALIDADO BOOLEAN DEFAULT FALSE,
    FECHA_VALIDACION TIMESTAMP,
    VALIDADO_POR INTEGER REFERENCES USUARIOS(ID),
    METADATOS TEXT,
    UBICACION_GPS VARCHAR(100),
    CALIDAD_DATO INTEGER DEFAULT 100,
    SINCRONIZADO BOOLEAN DEFAULT FALSE,
    FECHA_SINCRONIZACION TIMESTAMP
);

-- Crear tabla ALERTAS
CREATE TABLE IF NOT EXISTS ALERTAS (
    ID SERIAL PRIMARY KEY,
    USUARIO_ID INTEGER NOT NULL REFERENCES USUARIOS(ID) ON DELETE CASCADE,
    TIPO_ALERTA VARCHAR(50) NOT NULL,
    TITULO VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    NIVEL_SEVERIDAD VARCHAR(20) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_RESOLUCION TIMESTAMP,
    ESTADO VARCHAR(20) DEFAULT 'Pendiente',
    RESUELTO_POR INTEGER REFERENCES USUARIOS(ID),
    NOTAS_RESOLUCION TEXT,
    VALOR_TRIGGER DECIMAL(10,2),
    UMBRAL_CONFIGURADO DECIMAL(10,2),
    ACCIONES_RECOMENDADAS TEXT,
    PRIORIDAD INTEGER DEFAULT 1,
    NOTIFICADO BOOLEAN DEFAULT FALSE,
    FECHA_NOTIFICACION TIMESTAMP,
    CANAL_NOTIFICACION VARCHAR(50),
    METADATOS TEXT,
    REQUIERE_ATENCION_MEDICA BOOLEAN DEFAULT FALSE
);

-- Crear índices para optimizar consultas
CREATE INDEX IF NOT EXISTS idx_usuarios_email ON USUARIOS(EMAIL);
CREATE INDEX IF NOT EXISTS idx_usuarios_activo ON USUARIOS(ACTIVO);
CREATE INDEX IF NOT EXISTS idx_datos_vitales_usuario_fecha ON DATOS_VITALES(USUARIO_ID, FECHA_REGISTRO);
CREATE INDEX IF NOT EXISTS idx_datos_vitales_tipo ON DATOS_VITALES(TIPO_DATO);
CREATE INDEX IF NOT EXISTS idx_datos_vitales_fecha_medicion ON DATOS_VITALES(FECHA_MEDICION);
CREATE INDEX IF NOT EXISTS idx_alertas_usuario_estado ON ALERTAS(USUARIO_ID, ESTADO);
CREATE INDEX IF NOT EXISTS idx_alertas_fecha_creacion ON ALERTAS(FECHA_CREACION);
CREATE INDEX IF NOT EXISTS idx_alertas_nivel_severidad ON ALERTAS(NIVEL_SEVERIDAD);

-- Insertar usuario de prueba (ID: 7)
INSERT INTO USUARIOS (ID, NOMBRE, EMAIL, PASSWORD_HASH, ROL, ACTIVO) 
VALUES (7, 'Usuario Health Auto Export', 'healthautoexport@test.com', 'hash_placeholder', 'Usuario', true);

-- Insertar algunos usuarios adicionales para pruebas
INSERT INTO USUARIOS (NOMBRE, EMAIL, PASSWORD_HASH, ROL, ACTIVO) 
VALUES 
    ('Admin Sistema', 'admin@healthpredict.com', 'hash_admin', 'Admin', true),
    ('Doctor Ejemplo', 'doctor@healthpredict.com', 'hash_doctor', 'Medico', true),
    ('Usuario Demo', 'demo@healthpredict.com', 'hash_demo', 'Usuario', true);

-- Confirmar que las tablas se crearon correctamente
SELECT 'Tablas base creadas correctamente' AS resultado; 